### PR TITLE
Add support for 0AD A25

### PR DESCRIPTION
**Pull request by Jammyjamjamman**

### CODE REVIEW

**Comment by Jammyjamjamman** [comment]
#4 #5

**Comment by andy5995** [comment]
@Jammyjamjamman you are pretty much done with this and it's ready for play-testing?

**Comment by JustusAvramenko** [comment]
I don't know about code. But this branch seems to work as advertised to an end user. :)

**Comment by andy5995** [comment]
@JustusAvramenko thanks for testing

**Comment by Jammyjamjamman** [comment]
Me and Andy tested it in an online game and it worked so I'm happy for it to be merged. :)

**Pull request merged**
